---
title: '228 Practicum 3: Impact Evaluation'
author: "Danny Elkin, Eric Holmes, Molly Williams"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



### 0. Load required packages: 
```{r message=FALSE}
library(DeclareDesign)
library(truncnorm)
library(knitr)
library(tidyverse)

```


## Declare population

```{r}
set.seed(101)
population <- declare_population(
  restaurant = add_level(N=140, 
    baseline = runif(n=N, min=0.10, max=0.35), # a=min b = max
    annual_change = rnorm(n=N, mean=0.05, sd=0.1))
)

# some year to year variation; mean=0 means that on average stores will do the same thing 
# we think that the annual change will have some 

pop <- population()

# for annual change rate, how would we know the increase in awareness about sustanable seafood?

```


## Declare potential outcomes

```{r}

potential_outcomes <-
declare_potential_outcomes(
Y_Z_0 = baseline + annual_change, # we have an absolute change rather than a rate of change; business as usual scenario
Y_Z_1 = baseline + annual_change + 0.1) # treatment effect = whatever is additional to idiosyncratic changes ; we're saying 10% more sustainable seafood will be sold
# what is the minimum value where you still get a power of 0.8 
po <- potential_outcomes(pop)


```


## Potential outcomes descriptives 

```{r po-check, echo=TRUE}
mean(po$baseline) # mean increase of ~0.23
sd(po$baseline) # SD = 0.07, small amount of between-store variation

```


## Declare sample size
How many units are you actually going to bring into the study?
```{r}
sampling <- declare_sampling(n=140) 
sam <- sampling(po) # outcome of the function

# if your power is high enough, you could reduce N to reduce impact on RL

# you can advise them on what is the optimal sample size to get sufficient power

```


## Declare treatment assignment and reveal potential outcomes
```{r}

# Assign half the units to the treatment group
assigning <- declare_assignment(prob=0.5)
assigned <- assigning(sam)


# Declare  how the potential outcomes are revealed by the random assignment
revealing <- declare_reveal()

```


## Declare estimand and estimator

```{r}

# what is our target treatment effect?

estimand <- declare_estimand(
prop.change = mean(Y_Z_1-Y_Z_0)) # instead of normalizing by the baseline, look at store sales overall
estimand(po) # matches our expected treatment effect of 10% increase in proportion of sustainable seafood bought

dip <- declare_estimator(Y ~ Z + baseline, # looking at difference in sales proportion by store controlling for baseline value of the store and removing inter-store variation
estimand = estimand,
model = lm_robust, label = "DIP")
```

## Declare and diagnose design
```{r}
design <- population + potential_outcomes + sampling +
assigning + revealing + estimand + dip

diagnosis <- diagnose_design(design)
diagnosis$diagnosands_df[,c(1,3,5,9,11)] %>%
kable()

diagnosis$diagnosands_df %>% 
  kable()


# table shows power and whether there is bias ; maybe we don't need all 700 samples
# instead of treating half, they only want to treat 10% bc they want to be careful in rolling this out 

# Visualize estimates 
hist(diagnosis$simulations_df$estimate)

```



